### ISSUE TITLE
picocli の Kotlin 向けサンプルコードが動かない

### ISSUE THREAD

**Issue by okkez** [clear-code/statistics#107]
http://picocli.info/#_kotlin

`private val ...` じゃなくて `private var ...` にしないといけないみたい。

**Comment by cosmo0920** [comment]
```log
Exception in thread "main" picocli.CommandLine$InitializationException: Constant (final) primitive and String fields like private final int picocli.example.MyApp.count cannot be used as an @Option: compile-time constant inlining may hide new values written to it.
	at picocli.CommandLine.init(CommandLine.java:1964)
	at picocli.CommandLine$Interpreter.<init>(CommandLine.java:2040)
	at picocli.CommandLine.<init>(CommandLine.java:178)
	at picocli.CommandLine.<init>(CommandLine.java:167)
	at picocli.CommandLine.run(CommandLine.java:971)
	at picocli.CommandLine.run(CommandLine.java:925)
	at picocli.example.MyApp$Companion.main(MyApp.kt:29)
	at picocli.example.MyApp.main(MyApp.kt)

Process finished with exit code 1
```

サンプルコードを切り出して実行する環境を整えたら再現しました。

**Comment by cosmo0920** [comment]
プルリクエストにしました。 https://github.com/remkop/picocli/pull/273
以降はそちらで対応します。
