### ISSUE TITLE
fluent-plugin-pgjson: pg 1.0.0で動かない

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#117]
```text
2018-02-01 11:52:24 +0900 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-02-01 11:52:25 +0900 chunk="5641d9e65c4330bdcc74b923a64c27a8" error_class=RuntimeError error="failed to initialize connection: uninitialized constant Fluent::PgJsonOutput::PGconn"
  2018-02-01 11:52:24 +0900 [warn]: #0 /tmp/local/lib/ruby/gems/2.6.0/gems/fluent-plugin-pgjson-0.0.8/lib/fluent/plugin/out_pgjson.rb:71:in `rescue in init_connection'
  2018-02-01 11:52:24 +0900 [warn]: #0 /tmp/local/lib/ruby/gems/2.6.0/gems/fluent-plugin-pgjson-0.0.8/lib/fluent/plugin/out_pgjson.rb:64:in `init_connection'
  2018-02-01 11:52:24 +0900 [warn]: #0 /tmp/local/lib/ruby/gems/2.6.0/gems/fluent-plugin-pgjson-0.0.8/lib/fluent/plugin/out_pgjson.rb:41:in `write'
  2018-02-01 11:52:24 +0900 [warn]: #0 /tmp/local/lib/ruby/gems/2.6.0/gems/fluentd-1.1.0/lib/fluent/compat/output.rb:131:in `write'
  2018-02-01 11:52:24 +0900 [warn]: #0 /tmp/local/lib/ruby/gems/2.6.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1094:in `try_flush'
  2018-02-01 11:52:24 +0900 [warn]: #0 /tmp/local/lib/ruby/gems/2.6.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1319:in `flush_thread_run'
  2018-02-01 11:52:24 +0900 [warn]: #0 /tmp/local/lib/ruby/gems/2.6.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-02-01 11:52:24 +0900 [warn]: #0 /tmp/local/lib/ruby/gems/2.6.0/gems/fluentd-1.1.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by okkez** [comment]
別件で出しているPR上でメンテナンスを引き取れないか交渉中。

**Comment by okkez** [comment]
報告だけしておいた。
https://github.com/choplin/fluent-plugin-pgjson/issues/15
