### ISSUE TITLE
cssselect: "|E"がシンタックスエラーになる

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#145]
https://github.com/scrapy/cssselect

```text
>>> cssselect.xpath.GenericTranslator().css_to_xpath("|html")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kou/work/python/cssselect/cssselect/xpath.py", line 192, in css_to_xpath
    for selector in parse(css))
  File "/home/kou/work/python/cssselect/cssselect/parser.py", line 355, in parse
    return list(parse_selector_group(stream))
  File "/home/kou/work/python/cssselect/cssselect/parser.py", line 368, in parse_selector_group
    yield Selector(*parse_selector(stream))
  File "/home/kou/work/python/cssselect/cssselect/parser.py", line 376, in parse_selector
    result, pseudo_element = parse_simple_selector(stream)
  File "/home/kou/work/python/cssselect/cssselect/parser.py", line 475, in parse_simple_selector
    "Expected selector, got %s" % (peek,))
cssselect.parser.SelectorSyntaxError: Expected selector, got <DELIM '|' at 0>
```

https://www.w3.org/TR/selectors-3/#typenmsp

> |E
>    elements with name E without a namespace

**Comment by fujimotos** [comment]
アップストリームに報告を投げました。
https://github.com/scrapy/cssselect/issues/84
