### ISSUE TITLE
Zulip: 全角文字の直後のURLもオートリンクして欲しい

### ISSUE THREAD

**Issue by kou** [clear-code/statistics#69]
「日本語https://localhost/」みたいなやつ。

現状だと、「日本語」の後にスペースをいれないといけない。

**Comment by okkez** [comment]
https://github.com/zulip/zulip/blob/8f190e074629d8a6e8ece14bd5ae1376ebb6aa84/zerver/lib/bugdown/__init__.py#L1401 らへんにすごい正規表現があった。

↓にテストコードがあるっぽい。
https://github.com/zulip/zulip/blob/3f4bf2d22f4ee55f4c0c4027bdcac2ab6e3723ed/zerver/tests/test_bugdown.py#L1091

**Comment by okkez** [comment]
たぶん正規表現の最初のところに `\w` を足せば動くはず。

**Comment by okkez** [comment]
手元で今のテストを動かしてから修正を始めようとしたけど、手元でテストを走らせることができなかったので、travis-ci上で試すことにする。

**Comment by okkez** [comment]
```
FAIL: test_bugdown_fixtures (zerver.tests.test_bugdown.BugdownTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.4.6/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/opt/python/3.4.6/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "/home/travis/build/okkez/zulip/zerver/tests/test_bugdown.py", line 233, in test_bugdown_fixtures
    self.assertEqual(converted, test['expected_output'])
  File "/opt/python/3.4.6/lib/python3.4/unittest/case.py", line 800, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/python/3.4.6/lib/python3.4/unittest/case.py", line 1173, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/opt/python/3.4.6/lib/python3.4/unittest/case.py", line 645, in fail
    raise self.failureException(msg)
AssertionError: '<p>&[17 chars]p://x<a href="http://x.com/xss.js&lt;b" target[68 chars]</p>' != '<p>&[17 chars]p://xx.com/xss.js&lt;b&gt;</p>'
- <p>&lt;script src=http://x<a href="http://x.com/xss.js&lt;b" target="_blank" title="http://x.com/xss.js&lt;b">x.com/xss.js&lt;b</a>&gt;</p>
+ <p>&lt;script src=http://xx.com/xss.js&lt;b&gt;</p>
```

修正を入れてみたら↑だけ失敗するようになった。

**Comment by okkez** [comment]
フィードバックした。 
https://github.com/zulip/zulip/issues/7740
