### ISSUE TITLE
fluentd: システムを再起動するたびに起動に失敗する

### ISSUE THREAD

**Issue by fujimotos** [clear-code/statistics#87]
`/var/run` はリブートのたびにまるごと再生成されるディレクトリなので、毎回作らないといけない。
現在はtd-agentの「インストール時」に一発作っているだけなので、次のリブート以降からこける。

これは`td-agent.service`に一行追加してやれば済むはず：

```
RuntimeDirectory=/var/run/td-agent/
```

が、systemd用のサービスファイルをどこでリビジョン管理しているのかが分からない。

**Comment by fujimotos** [comment]
**参考: エラーログ**

```
fluentd[1474]: Unexpected error No such file or directory @ rb_sysopen - /var/run/td-agent/td-agent.pid
fluentd[1474]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.0.5/lib/serverengine/daemon.rb:200:in `initialize'
fluentd[1474]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.0.5/lib/serverengine/daemon.rb:200:in `open'
fluentd[1474]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.0.5/lib/serverengine/daemon.rb:200:in `write_pid_file'
fluentd[1474]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.0.5/lib/serverengine/daemon.rb:193:in `daemonize_with_double_fork'
fluentd[1474]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.0.5/lib/serverengine/daemon.rb:107:in `main'
fluentd[1474]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.0.5/lib/serverengine/daemon.rb:68:in `run'
fluentd[1474]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.25/lib/fluent/supervisor.rb:606:in `supervise'
fluentd[1474]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.25/lib/fluent/supervisor.rb:476:in `run_supervisor'
fluentd[1474]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.25/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
fluentd[1474]:   /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
fluentd[1474]:   /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
fluentd[1474]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.25/bin/fluentd:8:in `<top (required)>'
fluentd[1474]:   /opt/td-agent/embedded/bin/fluentd:22:in `load'
fluentd[1474]:   /opt/td-agent/embedded/bin/fluentd:22:in `<main>'
systemd[1]: td-agent.service: Control process exited, code=exited status=1
systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.
```

**Comment by fujimotos** [comment]
upstreamで既に修正済み
