### ISSUE TITLE
firefox: mk_add_options MOZ_CO_LOCALES=jaでビルドエラー

### ISSUE THREAD

**Issue by kenhys** [clear-code/statistics#95]
## Problem

nightlyをja有効でビルドしようとしてみたらエラーになった。
なんとなくこんな感じでやればビルドできそう、というのを試しただけなので正攻法ではないかもしれない。

## Actual

mozconfigは以下。

https://hg.mozilla.org/l10n-central/ja/ をl10n-baseに使っている。

```
% cat mozconfig
#mk_add_options AUTOCLOBBER=1

mk_add_options MOZ_CO_LOCALES=ja
ac_add_options --enable-ui-locale=ja
#ac_add_options --with-l10n-base=$HOME/work/firefox/gecko-l10n.work
ac_add_options --with-l10n-base=$HOME/work/firefox/l10n-central
#ac_add_options --disable-tests
#ac_add_options --disable-gtest-in-build
```

`src_base` がNoneなのでたぶん手順に問題がありそう。

```
10:37.66 Traceback (most recent call last):
10:37.66   File "/home/kenhys/.pyenv/versions/2.7.13/lib/python2.7/runpy.py", line 174, in _run_module_as_main
10:37.66     "__main__", fname, loader, pkg_name)
10:37.66   File "/home/kenhys/.pyenv/versions/2.7.13/lib/python2.7/runpy.py", line 72, in _run_code
10:37.66     exec code in run_globals
10:37.66   File "/home/kenhys/work/firefox/gecko-dev.work/python/mozbuild/mozbuild/action/jar_maker.py", line 17, in <module>
10:37.66     sys.exit(main(sys.argv[1:]))
10:37.66   File "/home/kenhys/work/firefox/gecko-dev.work/python/mozbuild/mozbuild/action/jar_maker.py", line 13, in main
10:37.66     return mozbuild.jar.main(args)
10:37.66   File "/home/kenhys/work/firefox/gecko-dev.work/python/mozbuild/mozbuild/jar.py", line 608, in main
10:37.66     jm.makeJar(infile, options.d)
10:37.66   File "/home/kenhys/work/firefox/gecko-dev.work/python/mozbuild/mozbuild/jar.py", line 333, in makeJar
10:37.66     self.processJarSection(info, jardir)
10:37.66   File "/home/kenhys/work/firefox/gecko-dev.work/python/mozbuild/mozbuild/jar.py", line 388, in processJarSection
10:37.66     self._processEntryLine(e, outHelper, jf)
10:37.66   File "/home/kenhys/work/firefox/gecko-dev.work/python/mozbuild/mozbuild/jar.py", line 452, in _processEntryLine
10:37.66     for _srcdir in src_base:
10:37.66 TypeError: 'NoneType' object is not iterable
10:37.67 /home/kenhys/work/firefox/gecko-dev.work/config/rules.mk:1241: recipe for target 'libs' failed
10:37.67 make[4]: *** [libs] Error 1
10:37.67 /home/kenhys/work/firefox/gecko-dev.work/config/recurse.mk:100: recipe for target 'netwerk/locales/libs' failed
10:37.67 make[3]: *** [netwerk/locales/libs] Error 2
10:37.67 /home/kenhys/work/firefox/gecko-dev.work/config/recurse.mk:32: recipe for target 'libs' failed
10:37.67 make[2]: *** [libs] Error 2
10:37.67 /home/kenhys/work/firefox/gecko-dev.work/config/rules.mk:434: recipe for target 'default' failed
10:37.67 make[1]: *** [default] Error 2
10:37.67 client.mk:168: recipe for target 'build' failed
10:37.67 make: *** [build] Error 2
10:37.69 40 compiler warnings present.
```

## Expected

`./mach build`でjaなやつもビルドできる。

**Comment by kenhys** [comment]
https://hg.mozilla.org/l10n-central/ja/

**Comment by ashie** [comment]
```
$ hg clone https://hg.mozilla.org/l10n-central/ja/
```

して

```
mk_add_options MOZ_CO_LOCALES=ja
ac_add_options --enable-ui-locale=ja
ac_add_options --with-l10n-base=/path/to/l10n-central/ja
```

を追加してビルドしたところ再現した

**Comment by ashie** [comment]
http://www.clear-code.com/blog/2015/9/4.html

**Comment by ashie** [comment]
似たような報告事例があったけど、何も解決していない https://bugzilla.mozilla.org/show_bug.cgi?id=1402564

**Comment by ashie** [comment]
今のソースの中に`MOZ_CO_LOCALES`なんて文字列は見当たらない。
https://dxr.mozilla.org/ で見るとESR24辺りが最後。

**Comment by ashie** [comment]
[mozilla-build](https://hg.mozilla.org/mozilla-build/)の中にも見当たらない。

http://www.clear-code.com/blog/2017/10/12.html の`MOZ_CO_LOCALES`に関する記述は嘘かも?

**Comment by ashie** [comment]
https://firefox-source-docs.mozilla.org/build/buildsystem/locales.html

**Comment by ashie** [comment]
[Bug 1402564: Remove --enable-ui-locale option from configure](https://bugzilla.mozilla.org/show_bug.cgi?id=1402564)

**Comment by ashie** [comment]
↑ あ、これ既に貼ってやった奴か

https://bugzilla.mozilla.org/show_bug.cgi?id=1402564#c3
ということらしい。

**Comment by ashie** [comment]
まとめると

* localeビルドはもうサポートしてない
    * `--enable-ui-locale`は削除されるだろう
* l10n版はen_US版を作ってからrepackでやってね
    * 方法は https://firefox-source-docs.mozilla.org/build/buildsystem/locales.html を参照
* `MOZ_CO_LOCALES`は随分前に無くなってそうだからククログの記述直した方が良いかも（未確認）

**Comment by ashie** [comment]
ドキュメントは用意されているし、`--enable-ui-locale`削除するというBugも立ってるので、特にフィードバックの必要は無さそう。
ククログのネタにでもするか。
